@base = http://localhost:8080

###
# @name linyz_jwt_token
POST {{base}}/users/create
Content-Type: application/json

{
    "name": "linyz",
    "email": "linyz@example.com",
    "gender": "male",
    "teenager": false,
    "password": "password123"
}
###
# @name uu_jwt_token
POST {{base}}/users/create
Content-Type: application/json

{
    "name": "uu",
    "email": "uu@example.com",
    "gender": "female",
    "teenager": false,
    "password": "password123"
}
###
# @name alice_jwt_token
POST {{base}}/users/create
Content-Type: application/json

{
    "name": "alice",
    "email": "alice@example.com",
    "gender": "female",
    "teenager": false,
    "password": "password123"
}
###
POST {{base}}/users/create
Content-Type: application/json

{
    "name": "bob",
    "email": "bob@example.com",
    "teenager": false,
    "password": "password123"
}
###
# @name bob_jwt_token
POST {{base}}/users/create
Content-Type: application/json

{
    "name": "bob",
    "email": "bob@example.com",
    "gender": "male",
    "teenager": false,
    "password": "password123"
}
###
# @name tom_jwt_token
POST {{base}}/users/create
Content-Type: application/json

{
    "name": "tom",
    "email": "tom@example.com",
    "gender": "male",
    "teenager": false,
    "password": "password123"
}
###

GET {{base}}/users/list
Accept: application/json


###
GET {{base}}/users/list_with_query?limit=4
Accept: application/json

###

POST {{base}}/users/signin
Content-Type: application/json

{
    "email": "linyz@exmple.com",
    "password": "password123"
}

###
POST {{base}}/users/create_chat
Authorization: Bearer {{linyz_jwt_token.response.body.token}}
Content-Type: application/json

{
    "chat_id": 1,
    "chat_name": "rust-study"
}

###
POST {{base}}/users/create_chat
Authorization: Bearer {{uu_jwt_token.response.body.token}}
Content-Type: application/json

{
    "chat_id": 1,
    "chat_name": "lalalal"
}
###
POST {{base}}/users/join_chat
Authorization: Bearer {{uu_jwt_token.response.body.token}}
Content-Type: application/json

{
    "chat_id": 1
}


### upload file
POST {{base}}/users/message/upload_file/1
Authorization: Bearer {{linyz_jwt_token.response.body.token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data;filename="cats.PNG"
Content-Type: application/octet-stream

< /Users/linyz/snapshot/cats.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"

Hello, world!
--MyBoundary--

###
GET {{base}}/users/message/files/1/943/a70/2d06f34599aee1f8da8ef9f7296031d699.txt
Authorization: Bearer {{linyz_jwt_token.response.body.token}}

###
POST {{base}}/users/message/send_message/1
Authorization: Bearer {{linyz_jwt_token.response.body.token}}
Content-Type: application/json

{
    "content": "Hello, this is a message with files.",
    "files": ["/tmp/chat_server/1/file/116/544/8a23b0408bf7df190550192193988d592e.PNG",
    "/tmp/chat_server/1/file/943/a70/2d06f34599aee1f8da8ef9f7296031d699.txt"]
}
###

POST http://localhost:8080/route
Content-Type: application/json

{
    "url": "https://google.com"
}


###


GET http://127.0.0.1:8080/redirect/jcu0sA

###